site_name: hiproxy documentation
site_author: zdying
site_description: hiproxy documentation. hiproxy is a lightweight proxy tool based on Node.js that supports an NGINX-like configuration.
theme: null
theme_dir: 'custom_theme'
google_analytics: ['UA-103231920-1', 'auto']
repo_url: 'https://github.com/hiproxy/hiproxy'

pages:
- 首页: 'zh/index.md'
- 快速开始:
    - 'hiproxy简介': 'zh/get_started/introduction.md'
    - '安装': 'zh/get_started/installation.md'
    - '运行示例项目': 'zh/get_started/run_example.md'
    - '运用到现有项目': 'zh/get_started/applied_to_existing_projects.md'
    - 'CLI选项': 'zh/get_started/cli_options.md'
- 配置:
    - '简介': 'zh/configuration/introduction.md'
    - '配置文件查找': 'zh/configuration/find_conf.md'
    - 'hosts': 'zh/configuration/hosts.md'
    - 'rewrite': 'zh/configuration/rewrite.md'
    - 'SSL/TLS证书配置': 'zh/configuration/ssl_certificate.md'
- Rewrite:
    - '简介': 'zh/configuration/rewrite_introduction.md'
    - '作用域': 'zh/configuration/rewrite_scope.md'
    - '内置指令': 'zh/configuration/rewrite_directive.md'
    - '内置变量': 'zh/configuration/rewrite_built_in_variable.md'
- Node.js API:
    - 'API': 'zh/api/api.md'
    - '事件': 'zh/api/events.md'
- 开发者:
    - '插件机制': 'zh/developer/plugin.md'
    - '扩展CLI命令': 'zh/developer/cli_command.md'
    - '扩展指令': 'zh/developer/directive.md'
    - '扩展页面': 'zh/developer/route.md'
- 常见问题:
    - 'FAQs': 'zh/faqs.md'