site_name: hiproxy
theme: null
theme_dir: 'custom_theme'
google_analytics: ['UA-103231920-1', 'auto']
repo_url: 'https://github.com/hiproxy/hiproxy'

pages:
- 首页: 'index.md'
- 快速开始:
    - 'hiproxy简介': 'get_started/introduction.md'
    - '安装': 'get_started/installation.md'
    - '运行示例项目': 'get_started/run_example.md'
    - '运用到现有项目': 'get_started/applied_to_existing_projects.md'
    - 'CLI选项': 'get_started/cli_options.md'
- 配置:
    - '简介': 'configuration/introduction.md'
    - '配置文件查找': 'configuration/find_conf.md'
    - 'hosts': 'configuration/hosts.md'
    - 'rewrite': 'configuration/rewrite.md'
    - 'SSL/TLS证书配置': 'configuration/ssl_certificate.md'
- Rewrite:
    - '简介': 'configuration/rewrite_introduction.md'
    - '作用域': 'configuration/rewrite_scope.md'
    - '内置指令': 'configuration/rewrite_directive.md'
    - '内置变量': 'configuration/rewrite_built_in_variable.md'
- Node.js API:
    - 'API': 'api/api.md'
    - '事件': 'api/events.md'
- 开发者:
    - '插件机制': 'developer/plugin.md'
    - '扩展CLI命令': 'developer/cli_command.md'
    - '扩展指令': 'developer/directive.md'
    - '扩展页面': 'developer/route.md'
- 常见问题:
    - 'FAQs': 'faqs.md'